/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TableColumnResizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  minColumnWidth: 50,
  maxColumnWidth: 500
};
var TableColumnResizerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.tableWidths = {};
    this.isResizing = false;
    this.currentTable = null;
    this.currentSourcePath = "";
    this.currentColumn = -1;
    this.startX = 0;
    this.startWidth = 0;
    this.handleMouseMove = (e) => {
      if (!this.isResizing || !this.currentTable)
        return;
      const deltaX = e.clientX - this.startX;
      const newWidth = Math.max(
        this.settings.minColumnWidth,
        Math.min(this.startWidth + deltaX, this.settings.maxColumnWidth)
      );
      this.setColumnWidth(this.currentTable, this.currentColumn, newWidth);
    };
    this.handleMouseUp = async () => {
      if (!this.isResizing)
        return;
      this.isResizing = false;
      document.removeEventListener("mousemove", this.handleMouseMove);
      document.removeEventListener("mouseup", this.handleMouseUp);
      document.body.classList.remove("table-resizing");
      if (this.currentTable) {
        this.currentTable.removeAttribute("data-resizing");
        await this.saveWidths(this.currentTable, this.currentSourcePath);
      }
      this.currentTable = null;
      this.currentSourcePath = "";
      this.currentColumn = -1;
    };
  }
  async onload() {
    var _a, _b;
    const raw = await this.loadData();
    const data = raw != null ? raw : {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data.settings) != null ? _a : {});
    this.tableWidths = (_b = data.tableWidths) != null ? _b : {};
    this.registerMarkdownPostProcessor((element, context) => {
      this.processTables(element, context);
    });
    this.addSettingTab(new TableColumnResizerSettingTab(this.app, this));
  }
  onunload() {
    document.removeEventListener("mousemove", this.handleMouseMove);
    document.removeEventListener("mouseup", this.handleMouseUp);
    document.body.classList.remove("table-resizing");
  }
  processTables(element, context) {
    if (!this.settings.enabled)
      return;
    element.querySelectorAll("table").forEach((table) => {
      this.makeTableResizable(table, context.sourcePath);
    });
  }
  makeTableResizable(table, sourcePath) {
    if (table.hasAttribute("data-resizable"))
      return;
    table.setAttribute("data-resizable", "true");
    this.applySavedWidths(table, sourcePath);
    const headerRow = table.rows[0];
    if (!headerRow)
      return;
    Array.from(headerRow.cells).forEach((cell) => {
      if (cell.cellIndex === headerRow.cells.length - 1)
        return;
      const handle = createEl("div", { cls: "table-column-resizer" });
      cell.appendChild(handle);
      handle.addEventListener("mousedown", (e) => {
        e.preventDefault();
        this.startResize(e, table, cell.cellIndex, sourcePath);
      });
    });
  }
  applySavedWidths(table, sourcePath) {
    const widths = this.tableWidths[this.getTableId(table, sourcePath)];
    if (!widths)
      return;
    table.setCssStyles({ tableLayout: "fixed" });
    Object.entries(widths).forEach(([columnIndex, width]) => {
      this.setColumnWidth(table, Number.parseInt(columnIndex, 10), width);
    });
  }
  startResize(e, table, columnIndex, sourcePath) {
    var _a;
    this.isResizing = true;
    this.currentTable = table;
    this.currentSourcePath = sourcePath;
    this.currentColumn = columnIndex;
    this.startX = e.clientX;
    const headerCell = (_a = table.rows[0]) == null ? void 0 : _a.cells[columnIndex];
    this.startWidth = headerCell ? headerCell.getBoundingClientRect().width : this.settings.minColumnWidth;
    table.setCssStyles({ tableLayout: "fixed" });
    table.setAttribute("data-resizing", "true");
    document.body.classList.add("table-resizing");
    document.addEventListener("mousemove", this.handleMouseMove);
    document.addEventListener("mouseup", this.handleMouseUp);
  }
  setColumnWidth(table, columnIndex, width) {
    const px = `${width}px`;
    Array.from(table.rows).forEach((row) => {
      const cell = row.cells[columnIndex];
      if (cell) {
        cell.setCssStyles({ width: px, minWidth: px, maxWidth: px });
      }
    });
  }
  async saveWidths(table, sourcePath) {
    const tableId = this.getTableId(table, sourcePath);
    const headerRow = table.rows[0];
    if (!headerRow)
      return;
    const widths = {};
    Array.from(headerRow.cells).forEach((cell) => {
      if (cell.style.width) {
        widths[cell.cellIndex] = Number.parseFloat(cell.style.width);
      }
    });
    if (Object.keys(widths).length === 0) {
      delete this.tableWidths[tableId];
    } else {
      this.tableWidths[tableId] = widths;
    }
    await this.saveData({ settings: this.settings, tableWidths: this.tableWidths });
  }
  /**
   * Stable id: source path + hash of the table's text content.
   * Widths survive restarts and edits elsewhere in the note; they reset
   * when the table's own content changes.
   */
  getTableId(table, sourcePath) {
    var _a;
    const content = (_a = table.textContent) != null ? _a : "";
    let hash = 5381;
    for (let i = 0; i < content.length; i++) {
      hash = (hash << 5) + hash + content.charCodeAt(i) >>> 0;
    }
    return `${sourcePath}::${hash.toString(36)}`;
  }
  async saveSettings() {
    await this.saveData({ settings: this.settings, tableWidths: this.tableWidths });
  }
};
var TableColumnResizerSettingTab = class extends import_obsidian.PluginSettingTab {
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable column resizing").setDesc("Drag column edges to resize tables in reading view.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Minimum column width").setDesc("Smallest allowed column width, in pixels.").addText(
      (text) => text.setValue(String(this.plugin.settings.minColumnWidth)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isNaN(parsed) && parsed > 0) {
          this.plugin.settings.minColumnWidth = parsed;
          if (this.plugin.settings.maxColumnWidth < parsed) {
            this.plugin.settings.maxColumnWidth = parsed;
          }
          await this.plugin.saveSettings();
          this.display();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Maximum column width").setDesc("Largest allowed column width, in pixels.").addText(
      (text) => text.setValue(String(this.plugin.settings.maxColumnWidth)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isNaN(parsed) && parsed > 0) {
          this.plugin.settings.maxColumnWidth = parsed;
          if (this.plugin.settings.minColumnWidth > parsed) {
            this.plugin.settings.minColumnWidth = parsed;
          }
          await this.plugin.saveSettings();
          this.display();
        }
      })
    );
  }
};
