/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TableColumnResizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  minColumnWidth: 50,
  maxColumnWidth: 500
};
var MAX_TABLE_ENTRIES_PER_FILE = 100;
function setElementCss(el, styles) {
  if (typeof el.setCssStyles === "function") {
    el.setCssStyles(styles);
  } else {
    Object.assign(el.style, styles);
  }
}
var TableColumnResizerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.tableWidths = {};
    this.isResizing = false;
    this.currentTable = null;
    this.currentSourcePath = "";
    this.currentColumn = -1;
    this.startX = 0;
    this.startWidth = 0;
    this.handlePointerMove = (e) => {
      if (!this.isResizing || !this.currentTable)
        return;
      const deltaX = e.clientX - this.startX;
      const newWidth = Math.max(
        this.settings.minColumnWidth,
        Math.min(this.startWidth + deltaX, this.settings.maxColumnWidth)
      );
      this.setColumnWidth(this.currentTable, this.currentColumn, newWidth);
    };
    this.handlePointerUp = () => {
      if (!this.isResizing)
        return;
      const table = this.currentTable;
      const sourcePath = this.currentSourcePath;
      this.endResize();
      if (table) {
        void this.saveWidths(table, sourcePath);
      }
    };
  }
  async onload() {
    var _a, _b;
    const raw = await this.loadData();
    const data = raw != null ? raw : {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data.settings) != null ? _a : {});
    this.tableWidths = (_b = data.tableWidths) != null ? _b : {};
    this.pruneStaleWidths();
    this.registerMarkdownPostProcessor((element, context) => {
      this.processTables(element, context);
    });
    this.addSettingTab(new TableColumnResizerSettingTab(this.app, this));
  }
  onunload() {
    this.endResize();
  }
  processTables(element, context) {
    if (!this.settings.enabled)
      return;
    element.querySelectorAll("table").forEach((table) => {
      this.makeTableResizable(table, context.sourcePath);
    });
  }
  makeTableResizable(table, sourcePath) {
    if (table.hasAttribute("data-resizable"))
      return;
    table.setAttribute("data-resizable", "true");
    this.applySavedWidths(table, sourcePath);
    const headerRow = table.rows[0];
    if (!headerRow)
      return;
    Array.from(headerRow.cells).forEach((cell) => {
      if (cell.cellIndex === headerRow.cells.length - 1)
        return;
      const handle = cell.createEl("div", { cls: "table-column-resizer" });
      handle.addEventListener("pointerdown", (e) => {
        this.onHandlePointerDown(e, table, cell.cellIndex, sourcePath);
      });
    });
  }
  applySavedWidths(table, sourcePath) {
    const widths = this.tableWidths[this.getTableId(table, sourcePath)];
    if (!widths)
      return;
    setElementCss(table, { tableLayout: "fixed" });
    const entries = Object.entries(widths);
    entries.forEach(([columnIndex, width]) => {
      this.setColumnWidth(table, Number.parseInt(columnIndex, 10), width);
    });
  }
  onHandlePointerDown(e, table, columnIndex, sourcePath) {
    var _a;
    if (this.isResizing || e.button !== 0)
      return;
    e.preventDefault();
    this.isResizing = true;
    this.currentTable = table;
    this.currentSourcePath = sourcePath;
    this.currentColumn = columnIndex;
    this.startX = e.clientX;
    const headerCell = (_a = table.rows[0]) == null ? void 0 : _a.cells[columnIndex];
    this.startWidth = headerCell ? headerCell.getBoundingClientRect().width : this.settings.minColumnWidth;
    setElementCss(table, { tableLayout: "fixed" });
    table.setAttribute("data-resizing", "true");
    document.body.classList.add("table-resizing");
    if (e.target instanceof Element) {
      try {
        e.target.setPointerCapture(e.pointerId);
      } catch (e2) {
      }
    }
    document.addEventListener("pointermove", this.handlePointerMove);
    document.addEventListener("pointerup", this.handlePointerUp);
    document.addEventListener("pointercancel", this.handlePointerUp);
  }
  endResize() {
    this.isResizing = false;
    document.removeEventListener("pointermove", this.handlePointerMove);
    document.removeEventListener("pointerup", this.handlePointerUp);
    document.removeEventListener("pointercancel", this.handlePointerUp);
    document.body.classList.remove("table-resizing");
    if (this.currentTable) {
      this.currentTable.removeAttribute("data-resizing");
    }
    this.currentTable = null;
    this.currentSourcePath = "";
    this.currentColumn = -1;
  }
  setColumnWidth(table, columnIndex, width) {
    const px = `${width}px`;
    Array.from(table.rows).forEach((row) => {
      const cell = row.cells[columnIndex];
      if (cell) {
        setElementCss(cell, { width: px, minWidth: px, maxWidth: px });
      }
    });
  }
  async saveWidths(table, sourcePath) {
    const tableId = this.getTableId(table, sourcePath);
    const headerRow = table.rows[0];
    if (!headerRow)
      return;
    const widths = {};
    Array.from(headerRow.cells).forEach((cell) => {
      if (cell.style.width) {
        widths[cell.cellIndex] = Number.parseFloat(cell.style.width);
      }
    });
    if (Object.keys(widths).length === 0) {
      delete this.tableWidths[tableId];
    } else {
      this.tableWidths[tableId] = widths;
    }
    await this.saveData({ settings: this.settings, tableWidths: this.tableWidths });
  }
  /**
   * Stable id: source path + hash of the table's text content.
   * Widths survive restarts and edits elsewhere in the note; they reset
   * when the table's own content changes.
   */
  getTableId(table, sourcePath) {
    var _a;
    const content = (_a = table.textContent) != null ? _a : "";
    let hash = 5381;
    for (let i = 0; i < content.length; i++) {
      hash = (hash << 5) + hash + content.charCodeAt(i) >>> 0;
    }
    return `${sourcePath}::${hash.toString(36)}`;
  }
  /** Drop saved widths for files that no longer exist, and cap entries per file. */
  pruneStaleWidths() {
    const ids = Object.keys(this.tableWidths);
    if (ids.length === 0)
      return;
    const idsByFile = /* @__PURE__ */ new Map();
    for (const id of ids) {
      const sep = id.lastIndexOf("::");
      const path = sep === -1 ? id : id.slice(0, sep);
      if (!path)
        continue;
      const list = idsByFile.get(path);
      if (list)
        list.push(id);
      else
        idsByFile.set(path, [id]);
    }
    let removed = false;
    idsByFile.forEach((fileIds, path) => {
      if (!this.app.vault.getAbstractFileByPath(path)) {
        fileIds.forEach((id) => delete this.tableWidths[id]);
        removed = true;
        return;
      }
      if (fileIds.length > MAX_TABLE_ENTRIES_PER_FILE) {
        fileIds.slice(0, fileIds.length - MAX_TABLE_ENTRIES_PER_FILE).forEach((id) => delete this.tableWidths[id]);
        removed = true;
      }
    });
    if (removed) {
      void this.saveData({ settings: this.settings, tableWidths: this.tableWidths });
    }
  }
  async saveSettings() {
    await this.saveData({ settings: this.settings, tableWidths: this.tableWidths });
  }
  async setEnabled(value) {
    this.settings.enabled = value;
    if (!value)
      this.removeAllHandles();
    await this.saveSettings();
  }
  /** Make disabling take effect immediately instead of waiting for the next render. */
  removeAllHandles() {
    document.querySelectorAll("table[data-resizable]").forEach((table) => {
      table.removeAttribute("data-resizable");
    });
    document.querySelectorAll(".table-column-resizer").forEach((handle) => {
      handle.remove();
    });
  }
};
var TableColumnResizerSettingTab = class extends import_obsidian.PluginSettingTab {
  /** Declarative settings (Obsidian 1.13.0+): powers the settings search. */
  getSettingDefinitions() {
    return [
      {
        name: "Enable column resizing",
        desc: "Drag column edges to resize tables in reading view.",
        control: {
          type: "toggle",
          key: "enabled",
          defaultValue: DEFAULT_SETTINGS.enabled
        }
      },
      {
        name: "Minimum column width",
        desc: "Smallest allowed column width, in pixels.",
        control: {
          type: "number",
          key: "minColumnWidth",
          defaultValue: DEFAULT_SETTINGS.minColumnWidth,
          validate: (value) => value > 0 ? void 0 : "Must be a positive number."
        }
      },
      {
        name: "Maximum column width",
        desc: "Largest allowed column width, in pixels.",
        control: {
          type: "number",
          key: "maxColumnWidth",
          defaultValue: DEFAULT_SETTINGS.maxColumnWidth,
          validate: (value) => value > 0 ? void 0 : "Must be a positive number."
        }
      }
    ];
  }
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    switch (key) {
      case "enabled":
        await this.plugin.setEnabled(Boolean(value));
        return;
      case "minColumnWidth":
        this.plugin.settings.minColumnWidth = Number(value);
        break;
      case "maxColumnWidth":
        this.plugin.settings.maxColumnWidth = Number(value);
        break;
      default:
        return;
    }
    await this.plugin.saveSettings();
  }
  /** Legacy imperative settings UI for Obsidian versions before 1.13.0. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable column resizing").setDesc("Drag column edges to resize tables in reading view.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        await this.plugin.setEnabled(value);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Minimum column width").setDesc("Smallest allowed column width, in pixels.").addText(
      (text) => text.setValue(String(this.plugin.settings.minColumnWidth)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isNaN(parsed) && parsed > 0) {
          this.plugin.settings.minColumnWidth = parsed;
          if (this.plugin.settings.maxColumnWidth < parsed) {
            this.plugin.settings.maxColumnWidth = parsed;
          }
          await this.plugin.saveSettings();
          this.display();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Maximum column width").setDesc("Largest allowed column width, in pixels.").addText(
      (text) => text.setValue(String(this.plugin.settings.maxColumnWidth)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        if (!Number.isNaN(parsed) && parsed > 0) {
          this.plugin.settings.maxColumnWidth = parsed;
          if (this.plugin.settings.minColumnWidth > parsed) {
            this.plugin.settings.minColumnWidth = parsed;
          }
          await this.plugin.saveSettings();
          this.display();
        }
      })
    );
  }
};
